name: custom_lint
version: 0.4.6
description: Lint rules are a powerful way to improve the maintainability of a project. Custom Lint allows package authors and developers to easily write custom lint rules.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.3.0
  analyzer_plugin: ^0.11.3
  args: ^2.3.1
  async: ^2.8.2
  ci: ^0.1.0
  cli_util: ^0.4.0
  collection: ^1.16.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  meta: ^1.7.0
  package_config: ^2.0.2
  path: ^1.8.0
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.0
  rxdart: ^0.27.7
  uuid: ^4.1.0
  yaml: ^3.1.1
  build: ^2.3.1
  build_config: ^1.1.0
  source_gen: ^1.2.3
  glob: ^2.1.1
  hotreloader: ^3.0.5
  matcher: ^0.12.0
  source_span: ^1.8.0

dev_dependencies:
  ansi_styles: ^0.3.2+1
  benchmark_harness: ^2.2.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  test: ^1.20.2

executables:
  custom_lint: custom_lint
