name: custom_lint_analyzer_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 0.4.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  custom_lint:
    git:
      url: git@github.com:TheForwardThinkingCompany/custom_lint.git
      ref: "c800705"
